import dice
import math
from tkinter import *


top = Tk()
L1 = Label(top, text="Number of sides:")
E1 = Entry(top, bd =5)
L2 = Label(text="Number of dice:")
E2 = Entry(bd =5)
L3 = Label(text="Modifier for each die:")
E3 = Entry(bd =5)
L4 = Label(text="Result:")
v=StringVar()
L5 = Label(textvariable=v)
B1 = Button(text="Roll!", command=lambda: v.set(dice.roller(int(E1.get()), int(E2.get()), int(E3.get()))))
B2 = Button(text='d2', command=lambda: v.set(dice.d2()))
B3 = Button(text="d3", command=lambda: v.set(dice.d3()))
B4 = Button(text="d4", command=lambda: v.set(dice.d4()))
B6 = Button(text="d6", command=lambda: v.set(dice.d6()))
B8 = Button(text="d8", command=lambda: v.set(dice.d8()))
B10 = Button(text="d10", command=lambda: v.set(dice.d10()))
B20 = Button(text="d20", command=lambda: v.set(dice.d20()))
B100 = Button(text="d100", command=lambda: v.set(dice.d100()))
L1.grid(row=0, column=0, columnspan=1)
E1.grid(row=1, column=0, columnspan=1)
L2.grid(row=2, column=0, columnspan=1)
E2.grid(row=3, column=0, columnspan=1)
L3.grid(row=4, column=0, columnspan=1)
E3.grid(row=5, column=0, columnspan=1)
L4.grid(row=3, column=2, columnspan=1)
L5.grid(row=4, column=2, columnspan=1)
B1.grid(row=0, column=1, columnspan=1)
B2.grid(row=0, column=2, columnspan=1)
B3.grid(row=0, column=3, columnspan=1)
B4.grid(row=1, column=1, columnspan=1)
B6.grid(row=1, column=2, columnspan=1)
B8.grid(row=1, column=3, columnspan=1)
B10.grid(row=2, column=1, columnspan=1)
B20.grid(row=2, column=2, columnspan=1)
B100.grid(row=2, column=3, columnspan=1)

top.mainloop()
