import dice
import math
from tkinter import *


top = Tk()
top.geometry('300x250') #stops window resizing with different values of dice rolls
L1 = Label(top, text="Number of sides:")
E1 = Entry(top, bd =3)
L2 = Label(text="Number of dice:")
E2 = Entry(bd =3)
L3 = Label(text="Modifier for each die:")
E3 = Entry(bd =3)
L4 = Label(text="Total Modifier:")
E4 = Entry(bd =3)
L5 = Label(text="Result:")
if (E1.get() == ""):
	E1.insert(END, "0")
	E2.insert(END, "0")
	E3.insert(END, "0")
	E4.insert(END, "0")
v=StringVar()
L6 = Label(textvariable=v)
B1 = Button(text="Roll!", command=lambda: v.set(E2.get() + "d(" + E1.get() + '{:+}'.format(int(E3.get())) + ") " + '{:+}'.format(int(E4.get())) + " = "
	'{:+}'.format(dice.roller(int(E1.get()), int(E2.get()), int(E3.get())) + int(E4.get()))))
B2 = Button(text='d2', command=lambda: v.set("d2: " + str(dice.d2())))
B3 = Button(text="d3", command=lambda: v.set("d3: " + str(dice.d3())))
B4 = Button(text="d4", command=lambda: v.set("d4: " + str(dice.d4())))
B6 = Button(text="d6", command=lambda: v.set("d6: " + str(dice.d6())))
B8 = Button(text="d8", command=lambda: v.set("d8: " + str(dice.d8())))
B10 = Button(text="d10", command=lambda: v.set("d10: " + str(dice.d10())))
B20 = Button(text="d20", command=lambda: v.set("d20: " + str(dice.d20())))
B100 = Button(text="d100", command=lambda: v.set("d100: " + str(dice.d100())))
L1.grid(row=0, column=0, columnspan=1)
E1.grid(row=1, column=0, columnspan=1)
L2.grid(row=2, column=0, columnspan=1)
E2.grid(row=3, column=0, columnspan=1)
L3.grid(row=4, column=0, columnspan=1)
E3.grid(row=5, column=0, columnspan=1)
L4.grid(row=6, column=0, columnspan=1)
E4.grid(row=7, column=0, columnspan=1)
L5.grid(row=8, column=0, columnspan=1, sticky=W)
L6.grid(row=9, column=0, columnspan=1, sticky=W)
B1.grid(row=0, column=1, columnspan=1, sticky=W, padx = 10)
B2.grid(row=0, column=2, columnspan=1, sticky=W, padx = 10)
B3.grid(row=0, column=3, columnspan=1, sticky=W, padx = 10)
B4.grid(row=2, column=1, columnspan=1, sticky=W, padx = 10)
B6.grid(row=2, column=2, columnspan=1, sticky=W, padx = 10)
B8.grid(row=2, column=3, columnspan=1, sticky=W, padx = 10)
B10.grid(row=4, column=1, columnspan=1, sticky=W, padx = 10)
B20.grid(row=4, column=2, columnspan=1, sticky=W, padx = 10)
B100.grid(row=4, column=3, columnspan=1, sticky=W, padx = 10)

top.mainloop()
